# Generated by ./update.sh - do not update manually!
# Last updated: 2025-12-19
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "1.20.5";
    src = fetchurl {
      url = "https://download.mochi.cards/releases/Mochi-1.20.5-arm64.dmg";
      hash = "sha512-ASLjrO4EwOQk5rShu3Of5n/2ZHieAYm5NkC5R9IAwmB2Wn9/nrsB8oLPlMnNHPlFj7PLE0PYo6bPQFkAFcfsTA==";
    };
  };
  x86_64-darwin = {
    version = "1.20.5";
    src = fetchurl {
      url = "https://download.mochi.cards/releases/Mochi-1.20.5.dmg";
      hash = "sha512-/0OZgXnHUiLgqGFRn9oshPzfY9UyzJUCWKi3l7vPClYi+Yelue0OBhZau64sdo44k65Kq8Co4iYDrFZUGp1yUg==";
    };
  };
  x86_64-linux = {
    version = "1.20.5";
    src = fetchurl {
      url = "https://download.mochi.cards/releases/Mochi-1.20.5.AppImage";
      hash = "sha512-qP0V9K9ZsJxTBCuATOm+gY8qjgtVc9xKRcYBcWBgM9mPf1nZru8Wgrv5SjIE36uGzyrdyaQdcDE7mwqvFZLTLA==";
    };
  };
}
