#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p cacert curl yq nix

# Based on https://github.com/NixOS/nixpkgs/blob/b8bb9ea944ade313fe9288a521e155990f6ede4d/pkgs/by-name/fa/fastmail-desktop/update.sh

set -euo pipefail

cd "$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")"

linux_info=$(curl -fsS "https://download.mochi.cards/releases/latest-linux.yml")
darwin_info=$(curl -fsS "https://download.mochi.cards/releases/latest-mac.yml")

linux_version=$(yq -r '.version' <<<"$linux_info")
darwin_version=$(yq -r '.version' <<<"$darwin_info")

x86_64_linux_url="https://download.mochi.cards/releases/Mochi-$linux_version.AppImage"
aarch64_darwin_url="https://download.mochi.cards/releases/Mochi-$darwin_version-arm64.dmg"
x86_64_darwin_url="https://download.mochi.cards/releases/Mochi-$darwin_version.dmg"

x86_64_linux_hash=$(
  nix hash convert --hash-algo sha512 "$(
    yq -r --arg ver "$linux_version" '
      (.files | map(select(.url == ("Mochi-" + $ver + ".AppImage"))) | .[0].sha512)
    ' <<< "$linux_info"
  )"
)
aarch64_darwin_hash=$(
  nix hash convert --hash-algo sha512 "$(
    yq -r --arg ver "$darwin_version" '
      (.files | map(select(.url == ("Mochi-" + $ver + "-arm64.dmg"))) | .[0].sha512)
    ' <<< "$darwin_info"
  )"
)
x86_64_darwin_hash=$(
  nix hash convert --hash-algo sha512 "$(
    yq -r --arg ver "$darwin_version" '
      (.files | map(select(.url == ("Mochi-" + $ver + ".dmg"))) | .[0].sha512)
    ' <<< "$darwin_info"
  )"
)

echo "Updating to Mochi $darwin_version/$linux_version"

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "$darwin_version";
    src = fetchurl {
      url = "$aarch64_darwin_url";
      hash = "$aarch64_darwin_hash";
    };
  };
  x86_64-darwin = {
    version = "$darwin_version";
    src = fetchurl {
      url = "$x86_64_darwin_url";
      hash = "$x86_64_darwin_hash";
    };
  };
  x86_64-linux = {
    version = "$linux_version";
    src = fetchurl {
      url = "$x86_64_linux_url";
      hash = "$x86_64_linux_hash";
    };
  };
}
EOF
